import { AccountType } from "plaid";

// Define the structure for Budget Categories
type XClassification = {
    name: string;
    items: string[];
};

// Define the budget categories
export const xCategories: XClassification[] = [
    {
        name: "Entertainment",
        items: [
            "Adult Entertainment",
            "Aquarium",
            "Arcades and Amusement Parks",
            "Art Dealers and Galleries",
            "Arts and Entertainment",
            "Athletic Fields",
            "Baseball",
            "Basketball",
            "Batting Cages",
            "Beaches",
            "Billiards and Pool",
            "Boating",
            "Bowling",
            "Buildings and Structures",
            "Campgrounds and RV Parks",
            "Canoes and Kayaks",
            "Casinos and Gaming",
            "Circuses and Carnivals",
            "Combat Sports",
            "Cruises",
            "Dance",
            "Dance Halls and Saloons",
            "Entertainment",
            "Equestrian",
            "Fairgrounds and Rodeos",
            "Football",
            "Gardens",
            "Go Carts",
            "Golf",
            "Gun Ranges",
            "Gymnastics",
            "Gyms and Fitness Centers",
            "Hiking",
            "Historic Sites",
            "Hockey",
            "Hot Air Balloons",
            "Hunting and Fishing",
            "Lakes",
            "Landmarks",
            "Miniature Golf",
            "Monuments and Memorials",
            "Mountains",
            "Movie Theatres",
            "Museums",
            "Music and Show Venues",
            "Natural Parks",
            "Night Clubs",
            "Nightlife",
            "Outdoors",
            "Paintball",
            "Parks",
            "Party Centers",
            "Personal Trainers",
            "Picnic Areas",
            "Playgrounds",
            "Psychics and Astrologers",
            "Race Tracks",
            "Racquet Sports",
            "Racquetball",
            "Rafting",
            "Recreation Centers",
            "Rivers",
            "Rock Climbing",
            "Running",
            "Scuba Diving",
            "Skydiving",
            "Snow Sports",
            "Soccer",
            "Social Clubs",
            "Sports and Recreation Camps",
            "Sports Clubs",
            "Sports Venues",
            "Stadiums and Arenas",
            "Swimming",
            "Symphony and Opera",
            "Tennis",
            "Theatrical Productions",
            "Travel Agents and Tour Operators",
            "Water Sports",
            "Yoga and Pilates",
            "Zoo",
        ],
    },
    {
        name: "Financial",
        items: [
            "ACH",
            "ATM",
            "Acorns",
            "Bank Fees",
            "Betterment",
            "Billpay",
            "Cash Advance",
            "Chase QuickPay",
            "Check",
            "Coinbase",
            "Credit",
            "Credit Card",
            "Debit",
            "Deposit",
            "Digit",
            "Dwolla",
            "Excess Activity",
            "Foreign Transaction",
            "Fraud Dispute",
            "Insufficient Funds",
            "Interest Charged",
            "Interest Earned",
            "Internal Account Transfer",
            "Keep the Change Savings Program",
            "Late Payment",
            "Loan",
            "Overdraft",
            "PayPal",
            "Payroll",
            "Plaid",
            "Refund",
            "Save As You Go",
            "Square",
            "Square Cash",
            "Tax",
            "Third Party",
            "Venmo",
            "Wire",
            "Wire Transfer",
            "Withdrawal",
        ],
    },
    {
        name: "Food",
        items: [
            "Afghan",
            "African",
            "American",
            "Asian",
            "Australian",
            "Bagel Shop",
            "Bakery",
            "Bar",
            "Barbecue",
            "Beer, Wine and Spirits",
            "Brazilian",
            "Breakfast Spot",
            "Breweries",
            "Burgers",
            "Cafe",
            "Caribbean",
            "Chinese",
            "Coffee Shop",
            "Cuban",
            "Cupcake Shop",
            "Delis",
            "Dessert",
            "Distillery",
            "Donuts",
            "Eastern European",
            "Ethiopian",
            "Falafel",
            "Farmers Markets",
            "Fast Food",
            "Filipino",
            "Fish and Chips",
            "Food and Beverage Store",
            "Food Truck",
            "French",
            "Gastropub",
            "German",
            "Greek",
            "Health Food",
            "Hotel Lounge",
            "Ice Cream",
            "Indian",
            "Indonesian",
            "Internet Cafes",
            "Italian",
            "Jazz and Blues Cafe",
            "Japanese",
            "Juice Bar",
            "Karaoke",
            "Kids' Store",
            "Korean",
            "Latin American",
            "Mediterranean",
            "Mexican",
            "Middle Eastern",
            "Moroccan",
            "Pizza",
            "Portuguese",
            "Restaurants",
            "Scandinavian",
            "Seafood",
            "Specialty",
            "Sports Bar",
            "Steakhouses",
            "Supermarkets and Groceries",
            "Sushi",
            "Swiss",
            "Thai",
            "Turkish",
            "Vegan and Vegetarian",
            "Wine Bar",
            "Winery",
        ],
    },
    {
        name: "Healthcare",
        items: [
            "Acupuncture",
            "Alternative Medicine",
            "Anesthesiologists",
            "Blood Banks and Centers",
            "Cardiologists",
            "Chiropractors",
            "Counseling and Therapy",
            "Dentists",
            "Dermatologists",
            "Ear, Nose and Throat",
            "Emergency Services",
            "Family Medicine",
            "Gastroenterologists",
            "General Surgery",
            "Glasses and Optometrist",
            "Healthcare",
            "Healthcare Services",
            "Hospitals, Clinics and Medical Centers",
            "Internal Medicine",
            "Medical Supplies and Labs",
            "Mental Health",
            "Neurologists",
            "Nurses",
            "Nutritionists",
            "Obstetricians and Gynecologists",
            "Oncologists",
            "Ophthalmologists",
            "Optometrists",
            "Orthopedic Surgeons",
            "Pathologists",
            "Pediatricians",
            "Pharmacies",
            "Physical Therapy",
            "Physicians",
            "Plastic Surgeons",
            "Podiatrists",
            "Pregnancy and Sexual Health",
            "Psychiatrists",
            "Psychologists",
            "Radiologists",
            "Respiratory",
            "Urologists",
        ],
    },
    {
        name: "Housing",
        items: [
            "Architects",
            "Construction Supplies",
            "Doors and Windows",
            "Electric",
            "Fences, Fireplaces and Garage Doors",
            "Gas",
            "Hardware and Services",
            "Home Appliances",
            "Home Inspection Services",
            "Housewares",
            "Interior Design",
            "Kitchens",
            "Landscaping and Gardeners",
            "Lighting Fixtures",
            "Mobile Homes",
            "Movers",
            "Pest Control",
            "Plumbing",
            "Pools and Spas",
            "Rent",
            "Sanitary and Waste Management",
            "Storage",
            "Swimming Pool Maintenance and Services",
            "Tree Service",
            "Upholstery",
            "Water",
        ],
    },
    {
        name: "Personal",
        items: [
            "Accessories Store",
            "Adult",
            "Antiques",
            "Arts and Crafts",
            "Auctions",
            "Beauty Products",
            "Bookstores",
            "Boutique",
            "Cameras",
            "Cards and Stationery",
            "Children",
            "Classic and Antique Car",
            "Clothing and Accessories",
            "Computers and Electronics",
            "Convenience Stores",
            "Costumes",
            "Dance and Music",
            "Department Stores",
            "Digital Purchase",
            "Discount Stores",
            "Electrical Equipment",
            "Equipment Rental",
            "Flea Markets",
            "Florists",
            "Furniture and Home Decor",
            "Gift and Novelty",
            "Hardware Store",
            "Health Food",
            "Hobby and Collectibles",
            "Industrial Supplies",
            "Jewelry and Watches",
            "Kids' Store",
            "Laundry and Garment Services",
            "Lawn and Garden",
            "Lingerie Store",
            "Luggage",
            "Marine Supplies",
            "Massage Clinics and Therapists",
            "Men's Store",
            "Mobile Phones",
            "Music, Video and DVD",
            "Musical Instruments",
            "Newsstands",
            "Office Supplies",
            "Outlet",
            "Pawn Shops",
            "Pets",
            "Photos and Frames",
            "Piercing",
            "Shoe Store",
            "Shopping Centers and Malls",
            "Skin Care",
            "Spas",
            "Sporting Goods",
            "Swimwear",
            "Tanning Salons",
            "Tattooing",
            "Tobacco",
            "Toys",
            "Vintage and Thrift",
            "Warehouses and Wholesale Stores",
            "Wedding and Bridal",
            "Wholesale",
            "Women's Store",
        ],
    },
    {
        name: "Transportation",
        items: [
            "Airlines and Aviation Services",
            "Airports",
            "Auto Oil and Lube",
            "Auto Smog Check",
            "Auto Tires",
            "Auto Transmission",
            "Automotive",
            "Bicycles",
            "Boat",
            "Boat Dealers",
            "Bus Stations",
            "Car Appraisers",
            "Car Dealers and Leasing",
            "Car Parts and Accessories",
            "Car Service",
            "Car Wash and Detail",
            "Car and Truck Rentals",
            "Charter Buses",
            "Fuel Dealer",
            "Gas Stations",
            "Heliports",
            "Hostels",
            "Hotels and Motels",
            "Limos and Chauffeurs",
            "Lodges and Vacation Rentals",
            "Lodging",
            "Maintenance and Repair",
            "Mobile Homes",
            "Motorcycle, Moped and Scooter Repair",
            "Motorcycles, Mopeds and Scooters",
            "Parking",
            "Public Transportation Services",
            "Rail",
            "Ride Share",
            "Salvage Yards",
            "Taxi",
            "Tolls and Fees",
            "Transportation Centers",
            "Used Car Dealers",
        ],
    },
];

export const xAssetClasses: XClassification[] = [
    {
        name: "Cash",
        items: [AccountType.Depository, "cash"]
    },
    {
        name: "Equity",
        items: [AccountType.Investment, "equity", "mutual fund"]
    },
    {
        name: "Credit",
        items: [AccountType.Credit]
    },
    {
        name: "Loan",
        items: [AccountType.Loan]
    },
    {
        name: "Other",
        items: [AccountType.Other]
    },
    {
        name: "Crypto",
        items: ["cryptocurrency"]
    }
];